# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1d0dc5107d3fdccd842cbf8f751bd3bb75f220e5431c603754ad4eab714240ef9c0188491f5490db79f9673dd05a2042f25f7db1648aefa25b1da4ede1dd5f5

test:
  secret_key_base: 2ae3d51d9c389920e85dc04e16d843e54347777ba8689a623e84bc0e01301e8db66cae1324840e1114f061129df6a7642feec51b5c58eed707d008fa3a4e232a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
